version: '3'

services:
  app:
    build: .
    command: ["go", "run", "main.go"]
    ports:
      - "8081:8081"
    volumes:
      - ./app:/app

networks:
  default:
    external: true

volumes:
  db_data:
